setwd("C:\\Users\\aungkon\\Desktop\\stat")
head(swiss)
attach(swiss)
qqnorm(Fertility)
shapiro.test(Fertility)
model <- lm(Fertility ~ Agriculture + Education  + Catholic + Infant.Mortality, data = swiss)
summary(model)
qqnorm(model$residuals)
plot(model$fitted.values,model$residuals)
plot(Agriculture,model$residuals)
plot(Catholic,model$residuals)
plot(Infant.Mortality,model$residuals)

model <- lm(Fertility ~ Agriculture + Education  + Catholic + Infant.Mortality + I(Catholic^2)+ I(Catholic^3), data = swiss)
summary(model)
plot(model$residuals)
library(Rmisc)
data<- read.csv("Genotype.csv",header = T,fileEncoding="UTF-8-BOM")
aggregate(Act~as.factor(Gender)*as.factor(Genotype),FUN=var)
head(data)
attach(data)
qqnorm(Act)
model <- aov(Act~as.factor(Genotype)*as.factor(Gender),data=data)
summary(model)


data<- read.csv("pouch.csv",header = T,fileEncoding="UTF-8-BOM")
head(data)
attach(data)
qqnorm(Volume)
qqnorm(Frequency)
shapiro.test(Volume)
shapiro.test(Frequency)
mean(Volume)
mean(Frequency)
var(Volume)
var(Frequency)
cor.test(Volume,Frequency,alternative = "two.sided")

model <-lm(Volume~Frequency,data=data) 
summary(model)
qqnorm(model$residuals)
plot(model$fitted.values,model$residuals)
plot(Frequency,model$residuals)
model <-lm(Volume~Frequency+I(Frequency^2),data=data)
summary(model)
